### ISSUE TITLE
cfml.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

### ISSUE THREAD

**Issue by huxtableb** [jcberquist/sublimetext-cfml#76]
Started having this issue this morning and can't figure a work around.  On launching ST3:
"Error loading syntax file "Packages/CFML/syntaxes/cfml.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit"

Using CFML v0.22.0 on macOS 10.12.4

My computer required a reboot this morning so this might be some sort of caching issue.

**Comment by interwebZninja** [comment]
I also just started getting this error this morning 
CFML v0.22.0 / Win 10

**Comment by jcberquist** [comment]
@huxtableb @interwebZninja could you try closing any open CFML files and reopening them? It would be helpful to know if there is a particular file triggering the issue. 

The CFML syntax includes HTML, CSS, and JavaScript syntaxes in it, are either of you using any non default syntaxes for those languages? It is possible that one of those was updated recently and that is triggering the issue.

**Comment by huxtableb** [comment]
Yup, I removed some other HTML, CSS, and JS packages and looks like I'm back to normal.  Thanks!

**Comment by interwebZninja** [comment]
It appears to occur when opening any cfm/cfc file. Even the most simple with nothing but cfscript..

@huxtableb, do you know what packages you removed that took care of your issue?

**Comment by huxtableb** [comment]
CSS3 (y0ssar1an) and HTML5 (mrmartineau) and I think one more.

**Comment by interwebZninja** [comment]
Good call... the conflict is with CSS3. thx. Now I can get back to work.

**Comment by jcberquist** [comment]
@huxtableb that is helpful, I had been poking around at popular packages and I had just seen the CSS3 packages has been recently updated. The HTML5 one hasn't been modified in a long time.

**Comment by huxtableb** [comment]
Great!  Yup, back to work : )

**Comment by jcberquist** [comment]
FYI: The CSS3 package used in combination with the CFML package definitely causes the `Apparent recursion` error. From testing I do not see any particular additions to the CSS3 package that caused this, but it is rather just the size of the file involved and the way it is included in the CFML package that causes the issue. If I remove a few contexts from the CSS3 syntax file then it starts working again, and it doesn't seem to matter which ones are removed, just that the number of contexts is reduced.

I could only reproduce the issue on ST build 3126 - I could not reproduce it on 3131 (the latest dev build)  -  so it seems it has been resolved in the ST core at this point.

**Comment by apriantara** [comment]
I'm using ST 3 build 3126 and had this issue. As suggested by @huxtableb, I removed CSS3 (y0ssar1an) and HTML5 (mrmartineau) , then the problem is gone. Now i can back to work.

**Comment by jcberquist** [comment]
Closing this issue as there is a Sublime Text stable release (3143) where this issue does not occur.

**Comment by tomchiverton** [comment]
FYI still happens. Maybe the docs for this project needs to call out the incompatibility ?
